name: ci

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-11.0, ubuntu-latest]
        go-version: [1.17.2]
        ruby-version: [3.1]

    name: ${{ matrix.os }} / go-${{ matrix.go-version }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/checkout@v2

      - run: gem install puma

      - if: contains(matrix.os, 'macos')
        run: |
          sw_vers
          sudo mkdir -p /etc/resolver;
          sudo chmod 0775 /etc/resolver;
          sudo chown :staff /etc/resolver;

      - run: go mod download

      - run: go test -v -race -coverprofile=coverage.out -covermode=atomic -timeout=300s ./...
